version: '3.9'
services:
  application:
    image: randomman552/abacws-data-vis:latest
    container_name: abacws-data-visualiser
    labels:
      - traefik.enable=true
      - "traefik.http.services.abacws.loadbalancer.server.port=80"
      - "traefik.http.routers.abacws.rule=Host(`abacws.example.com`)"
      - "traefik.http.routers.abacws.entrypoints=http,https"
      - "traefik.http.routers.abacws.tls=true"
