version: '3.8'
services:
  # Database
  mongo:
    image: mongo
    container_name: abacws-mongo
    restart: always

  api:
    image: randomman552/abacws-data-api:latest
    container_name: abacws-api
    restart: always
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.abacws-api.loadbalancer.server.port=80"
      - "traefik.http.routers.abacws-api.rule=Host(`api.abacws.example.com`)"
      - "traefik.http.routers.abacws-api.entrypoints=https"
      - "traefik.http.routers.abacws-api.tls=true"

  visualiser:
    image: randomman552/abacws-data-visualiser:latest
    container_name: abacws-visualiser
    restart: always
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.abacws-visualiser.loadbalancer.server.port=80"
      - "traefik.http.routers.abacws-visualiser.rule=Host(`visualiser.abacws.example.com`)"
      - "traefik.http.routers.abacws-visualiser.entrypoints=https"
      - "traefik.http.routers.abacws-visualiser.tls=true"

  