version: '3.8'
services:
  # Database
  mongo:
    image: mongo
    container_name: dissertation-mongo
    restart: always
    volumes:
      - /path/to/data:/data/db
  
  # Application with traefik
  app:
    image: randomman552/abacws-data-vis:latest
    container_name: dissertation-app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dissertation.loadbalancer.server.port=80"
      - "traefik.http.routers.dissertation.rule=Host(`abacws.example.com`)"
      - "traefik.http.routers.dissertation.entrypoints=https"
      - "traefik.http.routers.dissertation.tls=true"