# We create all Docker images in one workflow to reduce GitHub lfs billing
name: Create and Push Docker Images
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository with lfs
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push API
      uses: docker/build-push-action@v2
      with:
        context: "{{ defaultContext }}:backend"
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/abacws-data-api:latest

    - name: Build and push visualiser
      uses: docker/build-push-action@v2
      with:
        context: "{{ defaultContext }}:frontend"
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/abacws-data-visualiser:latest
